Repository paritytech/primitives, pull requests merged in 2018-08, with the labels that each got.

#47 Move fixed-hash and uint to parity-common; remove tests crate
  .travis.yml
  Cargo.toml
  ethbloom/Cargo.toml
  ethereum-types/Cargo.toml
  ethereum-types/src/hash.rs
  ethereum-types/src/lib.rs
  ethereum-types/src/uint.rs
  fixed-hash/Cargo.toml
  fixed-hash/src/hash.rs
  fixed-hash/src/lib.rs
  tests/Cargo.toml
  tests/src/hash_tests.rs
  tests/src/lib.rs
  tests/src/serialization.rs
  tests/src/uint_tests.rs
  uint/Cargo.toml
  uint/build.rs
  uint/examples/modular.rs
  uint/src/lib.rs
  uint/src/uint.rs
Labels: A0-pleasereview, F4-tests, F6-refactor, M4-core

#50 Cleanup leftover from previous pr
  ethbloom/Cargo.toml
Labels: A2-insubstantial, A8-looksgood

#51 Use new uint version
  ethbloom/Cargo.toml
  ethereum-types/Cargo.toml
  ethereum-types/build.rs
  ethereum-types/src/hash.rs
  ethereum-types/src/lib.rs
  ethereum-types/src/uint.rs
Labels: A0-pleasereview, F6-refactor, M4-core

#52 Fix `ethbloom tests` by switching to `hex_literal crate` instead of `rustc-hex`
  ethbloom/Cargo.toml
  ethbloom/src/lib.rs
Labels: A0-pleasereview

#54 Load deps from crates (prep for publication)
  ethbloom/Cargo.toml
  ethereum-types/Cargo.toml
  no-std-tests/Cargo.toml
Labels: A2-insubstantial, A8-looksgood, M4-core
